
services:
  postgres:
    image: postgres
    container_name: postgres_container  
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWD}
      POSTGRES_USER: ${DB_USER}
      PGDATA: /var/lib/postgresql/data/DaHL
    volumes:
      - postgre:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgre: